---

- name: restart container
  lxd_container:
    name: "{{ lxcname }}"
    state: restarted


- name: restart services
  systemd: name={{ item }} state=restarted
  with_items:
    - "{{ services }}"


- name: restart system_services
  systemd: name={{ item.src }} state=restarted
  with_items:
    - "{{ system_services }}"

- name: reload services
  command: systemctl daemon-reload
