---

- name: create profile
  lxd_profile:
    name: "{{ lxcname }}"
    state: present
    config: {"security.privileged": "true"}
    devices:
      eth0:
        name: eth0
        nictype: bridged
        parent: lxdbr0
        type: nic
      eth4:
        type: nic
        name: eth4
        host_name: "{{ lxcname }}.1"
        nictype: p2p
        mtu: "9000"
      eth5:
        type: nic
        name: eth5
        host_name: "{{ lxcname }}.2"
        nictype: p2p
        mtu: "9000"
      logdir:
        path: /var/log
        source: /var/log/beluganos/{{ lxcname }}
        type: disk
      root:
        path: /
        pool: default
        type: disk
